# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doGTDProcess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='context',
            field=models.TextField(default='', help_text='Comma seperated list of contexts'),
        ),
    ]
